#Description
#acc_lim_x:x方向的加速度绝对值

#acc_lim_y:y方向的加速度绝对值,该值只有全向移动的机器人才需配置.

#acc_lim_th:旋转加速度的绝对值.

#max_trans_vel:平移速度最大值绝对值

#min_trans_vel:平移速度最小值的绝对值

#max_vel_x:x方向最大速度的绝对值

#min_vel_x:x方向最小值绝对值,如果为负值表示可以后退.

#max_vel_y:y方向最大速度的绝对值.

#min_vel_y:y方向最小速度的绝对值.

#max_rot_vel:最大旋转速度的绝对值.

#min_rot_vel:最小旋转速度的绝对值.

#yaw_goal_tolerance:到达目标点时偏行角允许的误差，单位弧度.

#xy_goal_tolerance:到达目标点时,在xy平面内与目标点的距离误差.

#latch_xy_goal_tolerance:设置为true,如果到达容错距离内,机器人就会原地旋转,即使转动是会跑出容错距离外.

#sim_time:向前仿真轨迹的时间.

#sim_granularity:步长,轨迹上采样点之间的距离,轨迹上点的密集程度.

#vx_samples:x方向速度空间的采样点数.

#vy_samples:y方向速度空间采样点数.

#vth_samples:旋转方向的速度空间采样点数.

#controller_frequency:发送给底盘控制移动指令的频率.

#path_distance_bias:定义控制器与给定路径接近程度的权重.

#goal_distance_bias:定义控制器与局部目标点的接近程度的权重.

#occdist_scale:定义控制器躲避障碍物的程度.

#stop_time_buffer:为防止碰撞,机器人必须提前停止的时间长度.

#scaling_speed:启动机器人底盘的速度.

#max_scaling_factor:最大缩放参数.

#publish_cost_grid:是否发布规划器在规划路径时的代价网格.如果设置为true,那么就会在~/cost_cloud话题上发布sensor_msgs/PointCloud2类型消息.

#oscillation_reset_dist:机器人运动多远距离才会重置振荡标记.

#prune_plan:机器人前进是是否清除身后1m外的轨迹.



TrajectoryPlannerROS:
  max_trans_vel: 0.40
  min_trans_vel: 0.01
  max_vel_x: 0.40
  min_vel_x: -0.20
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_rot_vel: 0.20
  min_rot_vel: -0.20
  acc_lim_x: 1.25
  acc_lim_y: 0.0
  acc_lim_theta: 5
  acc_lim_trans: 1.25

  prune_plan: false

  xy_goal_tolerance: 0.20
  yaw_goal_tolerance: 0.1
  trans_stopped_vel: 0.1
  rot_stopped_vel: 0.1
  sim_time: 3.0
  sim_granularity: 0.1
  angular_sim_granularity: 0.1
  path_distance_bias: 34.0
  goal_distance_bias: 24.0
  occdist_scale: 0.05
  twirling_scale: 0.0
  stop_time_buffer: 0.5
  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.2
  forward_point_distance: 0.3
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40

  use_dwa: true
  restore_defaults: false
